### ISSUE TITLE
v1.1.4 breaking change

### ISSUE THREAD

**Issue by KcZer0** [PEZ/paste-replaced#2]
Hi, 251010844a028da6408da7c83ed00b7316b09e73 introduced a breaking change, removing previous commands.
I usually check changelogs before updating, and expected it to work fine after updating, since the changelog doesn't mention any breaking change, only "Add" and no "Remove" or "Change".

But, it's not working as is, after update. 
Requiring changes to config **and** command change (for keyboard shortcut). 

Shouldn't it have been updated to v2 (major version) instead of only updating patch version? 

Also, I suggest at least updating minor version when adding/removing features like this (if no breaking change).
Update major version when introducing breaking changes, so that users can expect changes when updating.

**Comment by PEZ** [comment]
Hi! I am sorry. I didn't think about how breaking removing those commands were. Tbh, I thought no-one but me actually use this extension.

Now that I know I have a user, I'd like to ask about how you are using it?

I do hope I didn't change things so much that you can't use it? My aim here was to make it more versatile than it was before.

Again, entirely sorry! Will think about versioning and what to put in the changelog, going forward.

**Comment by KcZer0** [comment]
> Now that I know I have a user, I'd like to ask about how you are using it?

I frequently used regex replace, which I have to copy a search/replace string into each find and replace box whenever I want to do the replace.
Your extension (thanks btw!) helps so that I don't have to copy them every time, just putting it in the config once, then use the shortcut to do the replace. 

> I do hope I didn't change things so much that you can't use it?

Well, "breaking change" means *it can't be used*, as configured from previous version. 
Requiring users to change something, if updating to the version. 

I should still can use it, if reconfigured. But I haven't reconfiged it, since I haven't had the time. 
I think I only need to add the "name"? I'll probably do it next time, as recently I don't need to do the replace as often.

> Again, entirely sorry! Will think about versioning and what to put in the changelog, going forward.

It's fine, copy-pasting the find-replace string still works :). 
Checkout [semver.org](https://semver.org/#summary) and [VSCode Docs for publishing](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#autoincrementing-the-extension-version) about the versioning.

Still, thank you for making this extension.

**Comment by KcZer0** [comment]
I'll leave it to you to close this issue. 
If you can change/update the v1.1.4 to v2, in the vs marketplace? (I don't know how it works)

Or just closing this issue is fine with me.

**Comment by PEZ** [comment]
> means _it can't be used_, as configured from previous version.

I actually tried, and thought my testing confirmed, that the extension still should work as before with any old configuration. Maybe I can fix that.

As for commands being removed it doesn't sound like you used those? Maybe the reason things broke with 1.1.4 is a bug, rather than a deliberate change. If you can describe the steps you take when you use version 1.1.3, and what happens when you try that with 1.1.5, I might be able to figure out how to make it work again, without any changes on your part. (Then you might want to do the changes to use the new features, but that's another thing.)

**Comment by KcZer0** [comment]
Oh, just checked again, I just *disabled* (minus sigh) a shortcut for "selectWordLeftAndPasteReplaced" in keymap.json, and not assign any commands, sorry! I thought I assigned the `ctrl+alt+v  v` myself, turns out it's from the default. 
So, the breaking change turns out to be mainly caused by the config change, not command change  (just 

The are steps I did:
- Used `ctrl+alt+v  v` shortcut to replace. (1.1.3) 
- After updating to v1.1.5, the shortcut is gone (+ not mentioned in changelog). 
- Tried the new "Paste ...", doesn't work, "No named replacers". (expected to work with old array based config)
- Tried "Copy selected and paste ...", doesn't work. 
- Thus I opened this issue. 

I think the copy one does have a bug?
It either says "command execCopy not found" or "command paste-replaced:pasteSelectionReplaced not found"

**Comment by PEZ** [comment]
Thanks for the update! Totally appreciate it.

I've just released a new version that fixes the bug with backward compatibility with old config.

I also updated the Changelog retroactively about the keyboard shortcut change, it is now `ctrl+alt+v space`.

Will have to look a bit deeper on the copy selected and paste bug.
