### ISSUE TITLE
Command Copy Selected and Paste doesn't work

### ISSUE THREAD

**Issue by PEZ** [PEZ/paste-replaced#3]
Tried "Copy selected and paste ...", doesn't work. 

I think the copy one does have a bug?
It either says "command execCopy not found" or "command paste-replaced:pasteSelectionReplaced not found"

_Originally posted by @KcZer0 in https://github.com/PEZ/paste-replaced/issues/2#issuecomment-1312051966_

**Comment by KcZer0** [comment]
Hi, just updated to 1.1.8, this is still not fixed
(command execCopy not found)

Edit: Tried going back to v1.1.3 and same error, so it's probably only on my part
I'll comment again after I fix this.

**Comment by PEZ** [comment]
Not sure it is on your part, but that it doesn't work with 1.1.3 is interesting. Do you try the command in an editor or in a search box or something like that?
