### ISSUE TITLE
Nothing is working?

### ISSUE THREAD

**Issue by AndrewRocky** [PEZ/paste-replaced#4]
After setting up settings with:
```json
"paste-replaced.replacers": [
        {
            "name": "Quote strings and newlines",
            "replacements": [
                [ "a", "b", "g" ],
            ]
        }
    ],
```

When trying default `ctrl+alt+v space` VSCode throws notification with `command 'execPaste' not found` error.
When trying default `Paste Replaced: Copy Selected Text and Paste Replaced...` VSCode throws `command 'execCopy' not found` in an error window.
After that I've also tried adding custom keybindings (and removing default ones) in keybindings.json:
```json
    {
        // paste text from clipboard into terminal and remove newline at the end if exists
        "key": "ctrl+alt+v",
        "command": "paste-replaced.paste",
        // "when": "terminalFocus",
        "args": {
            "replacements": [
                [ "\n$", "", "g" ]
            ]
        }
    },
    {
        "key": "ctrl+alt+v space",
        "command": "-paste-replaced.paste"
    },
    {
        "key": "ctrl+alt+v escape",
        "command": "-paste-replaced.interruptTyping",
        "when": "paste-replaced.isTyping"
    },
```
And that throws same error as 1st one - `command 'execPaste' not found` both in terminal and normal editors.

I've tried both on normal local VSCode (Windows 21H2) and via official Remote Host Extension (client-Windows 21H2, host-Ubuntu 20.04) - same situation everywhere.

IDK if this is supposed to be like that but Paste Replaced in VSCode's output prints only `Paste Replace activating`

VSCode version - 1.73.1
Paste Replaced version - v1.1.8

**Comment by PEZ** [comment]
Hi there! Thanks for the detailed error report. Right now I don't know what's going on. We have a similar error mentioned in a comment on #3, but for that user paste seems to work.

Could be something is changing in VS Code. I am running on 1.73.0. Will try after upgrading.

> IDK if this is supposed to be like that but Paste Replaced in VSCode's output prints only `Paste Replace activating`

That's extra interesting. The extension should also print: `Paste Replace activate END`...

**Comment by PEZ** [comment]
Now restarted and am using 1.73.1. Things still work here, so even if this is a VS Code change, it doesn't affect all users...

Can you test if this is a regression from 1.1.3, @AndrewRocky? From your report it seems you should run into the same problem there. If so, it probably is about a VS Code change with some twists... 

Note that 1.1.3 had a different settings format. And I don't think it accepted arguments with the keyboard shortcuts.

**Comment by KcZer0** [comment]
> but for that user paste seems to work

Actually, it also doesn't work for me. 
I also get both error, `execPaste not found`  for command `Paste...` and `execCopy not found` `execCopy` for command `Copy Selected Text and Paste Replaced...`. 

The `Paste...` command actually did replace and copied the result to clipboard, it just can't paste because of `execPaste`

**Comment by KcZer0** [comment]
Oh... Accidentally found my local copy of the extension, which I completely forgot I had.  :) 
I just remembered that I actually modified your extension locally, fixing the execCopy and execPaste error. 
That's why I get the error even after reverting to v1.1.3, because the error was also there. 

I fixed it by using `editor.action.clipboard[Copy|Paste]Action` commands. 
Those were based on default keybindings for copy/paste (Command Palette > search `Default Keyboard Shortcuts`)

Changing those again locally fixes it. 
I'll open a pull request.

**Comment by PEZ** [comment]
As I remember things, those commands don't work in quickpick menus, etcetera.

**Comment by AndrewRocky** [comment]
I've tried a new 1.1.9 version and now extension Outputs this:
```txt
Paste Replace activating...
Paste Replace activation done
```
Errors are the same though. I'll try switching to 1.1.3 and report how things are working there.

(btw, about `editor.action.clipboard[Copy|Paste]Action` - it indeed only works in editor and for my use case (terminal) it won't be very useful)

**Comment by AndrewRocky** [comment]
I've tried 1.1.3 and it has the same result as 1.1.8. I've used these settings (form older readme):
```js
    "paste-replaced.replacers": [
        [
            [ "\"", "\\\"", "g" ],
            [ " +", " ", "g" ],
            [ "\n", "\\n", "g" ],
        ]
    ],
```

What's interesting - I've googled some stuff and noticed that command `execCopy` is often used in keybindings with `cmd+...` - meaning that mostly macOS users are using it - could it be that it's a macOS unique command?

I've also tried to run it on a normal Ubuntu (vscode v1.73.1)

Tried making a keybind:
```js
    {
        "key": "ctrl+alt+p",
        "command": "execCopy"
    }
```
And it also raises the same error - `command 'execCopy' not found`

**Comment by PEZ** [comment]
Thanks both of you! 🙏  Totally appreciate this help. So tricky to fix bugs that don't show up on my machine. I had no idea there could be different commands available for the same things on different platforms...

I'm releasing a new version now, v1.1.10. 🎉  It should show up in VS Code in a few minutes.

**Comment by PEZ** [comment]
If you want to hurt your eyes a bit more with ClojureScript code, I've made [a video of me hacking on this extension](https://www.youtube.com/watch?v=fMtvtAfdr90) to show a bit why I am using such a foreign (to some) language.

**Comment by AndrewRocky** [comment]
Thank you for support! Everything is working now on my machines.

**Comment by PEZ** [comment]
You are welcome, @AndrewRocky!

Can I ask what's your use case(s) for this extension?

**Comment by PEZ** [comment]
Both of you, @KcZer0 and @AndrewRocky . I've just submitted a PR adding commands for supporting canned text. If you like to help me test it, you are entirely welcome. There's a VSIX link in the PR text:

* https://github.com/PEZ/paste-replaced/pull/6

**Comment by AndrewRocky** [comment]
@PEZ I'm using it to insert commands into terminal without running them (replacing '\n$' with '')

**Comment by PEZ** [comment]
Thanks! I'm going to use that too!
